// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtQVKF6EZfAmWMIVf-FExIgM7wt8QMbY',
    appId: '1:862079318170:web:b3f55c3977d15a274e8723',
    messagingSenderId: '862079318170',
    projectId: 'css-chess-flutter',
    authDomain: 'css-chess-flutter.firebaseapp.com',
    storageBucket: 'css-chess-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC6alkmJpDs7pE0TtKDNZNjMJJE-LWbYA',
    appId: '1:862079318170:android:49cbf86d7023f7ee4e8723',
    messagingSenderId: '862079318170',
    projectId: 'css-chess-flutter',
    storageBucket: 'css-chess-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXtQVKF6EZfAmWMIVf-FExIgM7wt8QMbY',
    appId: '1:862079318170:web:55ad53a1aff49ea54e8723',
    messagingSenderId: '862079318170',
    projectId: 'css-chess-flutter',
    authDomain: 'css-chess-flutter.firebaseapp.com',
    storageBucket: 'css-chess-flutter.firebasestorage.app',
  );
}
